# Model arguments
model_name_or_path: princeton-nlp/Llama-3-Base-8B-SFT
torch_dtype: null
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  HuggingFaceH4/ultrafeedback_binarized: 1.0
dataset_splits:
- train_prefs
- test_prefs
preprocessing_num_workers: 12

# SimPOTrainer arguments
bf16: true
use_poet: true
beta: 0.01
do_eval: true
evaluation_strategy: steps
eval_steps: 400
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: False
hub_model_id: simpo-exps
learning_rate: 5.0e-7
log_level: info
logging_steps: 5
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
num_train_epochs: 1
optim: adamw_torch
output_dir: outputs/llama-3-8b-base-dpo-poet
run_name: llama-3-8b-base-dpo-poet
per_device_train_batch_size: 1
per_device_eval_batch_size: 2
push_to_hub: false
save_strategy: "epoch"
save_steps: 1000000
save_only_model: true
report_to:
- wandb
save_total_limit: 20
seed: 42
warmup_ratio: 0.1
